// LinkedIn Industry Categories
export const INDUSTRIES = [
  "Accounting",
  "Airlines/Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Apparel & Fashion",
  "Architecture & Planning",
  "Arts & Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Banking",
  "Biotechnology",
  "Broadcast Media",
  "Building Materials",
  "Business Supplies & Equipment",
  "Capital Markets",
  "Chemicals",
  "Civic & Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer & Network Security",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software",
  "Construction",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy",
  "Defense & Space",
  "Design",
  "E-learning",
  "Education Management",
  "Electrical & Electronic Manufacturing",
  "Entertainment",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Food & Beverages",
  "Food Production",
  "Fundraising",
  "Furniture",
  "Gambling & Casinos",
  "Glass, Ceramics & Concrete",
  "Government Administration",
  "Government Relations",
  "Graphic Design",
  "Health, Wellness & Fitness",
  "Higher Education",
  "Hospital & Health Care",
  "Hospitality",
  "Human Resources",
  "Import & Export",
  "Individual & Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology",
  "Insurance",
  "International Affairs",
  "International Trade & Development",
  "Internet",
  "Investment Banking",
  "Investment Management",
  "Judiciary",
  "Law Enforcement",
  "Law Practice",
  "Legal Services",
  "Legislative Office",
  "Leisure, Travel & Tourism",
  "Libraries",
  "Logistics & Supply Chain",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Management Consulting",
  "Maritime",
  "Marketing & Advertising",
  "Market Research",
  "Mechanical or Industrial Engineering",
  "Media Production",
  "Medical Device",
  "Medical Practice",
  "Mental Health Care",
  "Military",
  "Mining & Metals",
  "Motion Pictures & Film",
  "Museums & Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers",
  "Nonprofit Organization Management",
  "Oil & Energy",
  "Online Media",
  "Outsourcing/Offshoring",
  "Package/Freight Delivery",
  "Packaging & Containers",
  "Paper & Forest Products",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organization",
  "Primary/Secondary Education",
  "Printing",
  "Professional Training & Coaching",
  "Program Development",
  "Public Policy",
  "Public Relations & Communications",
  "Public Safety",
  "Publishing",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate",
  "Recreational Facilities & Services",
  "Religious Institutions",
  "Renewables & Environment",
  "Research",
  "Restaurants",
  "Retail",
  "Security & Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Sporting Goods",
  "Sports",
  "Staffing & Recruiting",
  "Software as a Service",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation & Localization",
  "Transportation/Trucking/Railroad",
  "Travel Arrangements & Tourism",
  "Utilities",
  "Venture Capital & Private Equity",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine & Spirits",
  "Wireless",
  "Writing & Editing",
];

// Industry Icons
export const INDUSTRY_ICONS = {
  // Technology & Software
  'Software as a Service (SaaS)': '🧑‍💻',
  'Computer Software': '💻',
  'Information Technology': '💻',
  'Computer & Network Security': '🔒',
  'Computer Hardware': '🖥️',
  'Computer Networking': '🌐',
  'Computer Games': '🎮',
  'Internet': '🌐',
  'Wireless': '📶',
  'Nanotechnology': '🔬',
  'Semiconductors': '🔌',
  'E-learning': '📚',
  'Online Media': '📱',

  // Telecommunications & Media
  'Telecommunications': '📡',
  'Broadcast Media': '📺',
  'Media Production': '🎥',
  'Motion Pictures & Film': '🎬',
  'Publishing': '📖',
  'Newspapers': '📰',
  'Music': '🎵',
  'Animation': '🎨',
  'Graphic Design': '🎨',
  'Photography': '📸',

  // Food & Beverage
  'Food & Beverages': '🥤',
  'Food Production': '🍞',
  'Restaurants': '🍽️',
  'Dairy': '🥛',
  'Supermarkets': '🛒',
  'Wine & Spirits': '🍷',

  // Automotive & Transportation
  'Automotive': '🚗',
  'Airlines/Aviation': '✈️',
  'Aviation & Aerospace': '🚀',
  'Transportation/Trucking/Railroad': '🚂',
  'Maritime': '🚢',
  'Package/Freight Delivery': '📦',
  'Logistics & Supply Chain': '📦',

  // Financial Services
  'Financial Services': '💳',
  'Banking': '🏦',
  'Capital Markets': '📈',
  'Investment Banking': '💰',
  'Investment Management': '📊',
  'Insurance': '🛡️',
  'Venture Capital & Private Equity': '💼',

  // Healthcare & Medicine
  'Hospital & Health Care': '🏥',
  'Medical Practice': '⚕️',
  'Medical Device': '🩺',
  'Pharmaceuticals': '💊',
  'Alternative Medicine': '🌿',
  'Mental Health Care': '🧠',
  'Veterinary': '🐾',

  // Education & Research
  'Education Management': '📚',
  'Higher Education': '🎓',
  'Primary/Secondary Education': '📝',
  'Research': '🔬',
  'Think Tanks': '💡',
  'Professional Training & Coaching': '🎯',

  // Manufacturing & Industry
  'Electrical & Electronic Manufacturing': '⚡',
  'Mechanical or Industrial Engineering': '⚙️',
  'Industrial Automation': '🤖',
  'Machinery': '🔧',
  'Building Materials': '🏗️',
  'Chemicals': '🧪',
  'Plastics': '🔄',
  'Textiles': '🧵',
  'Furniture': '🪑',
  'Glass, Ceramics & Concrete': '🏺',

  // Retail & Consumer Goods
  'Apparel & Fashion': '👕',
  'Consumer Electronics': '📱',
  'Consumer Goods': '🛍️',
  'Consumer Services': '🛎️',
  'Cosmetics': '💄',
  'Luxury Goods & Jewelry': '💎',
  'Sporting Goods': '⚽',
  'Wholesale': '📦',

  // Energy & Environment
  'Oil & Energy': '⛽',
  'Renewables & Environment': '🌱',
  'Environmental Services': '🌍',
  'Utilities': '⚡',

  // Government & Public Services
  'Government Administration': '🏛️',
  'Government Relations': '🤝',
  'Public Policy': '📜',
  'Public Safety': '🚨',
  'Law Enforcement': '👮',
  'Military': '🎖️',
  'Defense & Space': '🚀',

  // Legal & Professional Services
  'Law Practice': '⚖️',
  'Legal Services': '⚖️',
  'Alternative Dispute Resolution': '🤝',
  'Management Consulting': '💼',
  'Accounting': '📊',
  'Human Resources': '👥',
  'Staffing & Recruiting': '👔',

  // Real Estate & Construction
  'Real Estate': '🏠',
  'Commercial Real Estate': '🏢',
  'Construction': '🏗️',
  'Architecture & Planning': '📐',

  // Arts & Entertainment
  'Arts & Crafts': '🎨',
  'Performing Arts': '🎭',
  'Entertainment': '🎪',
  'Museums & Institutions': '🏛️',
  'Sports': '⚽',
  'Gambling & Casinos': '🎰',

  // Social Services & Non-Profit
  'Nonprofit Organization Management': '🤝',
  'Civic & Social Organization': '🌍',
  'Individual & Family Services': '👨‍👩‍👧‍👦',
  'Religious Institutions': '⛪',
  'Philanthropy': '💝',

  // Agriculture & Natural Resources
  'Farming': '🌾',
  'Ranching': '🐄',
  'Mining & Metals': '⛏️',
  'Forestry': '🌲',
  'Fishing': '🎣',

  // Other Services
  'Hospitality': '🏨',
  'Travel Arrangements & Tourism': '✈️',
  'Events Services': '🎉',
  'Facilities Services': '🏢',
  'Security & Investigations': '🕵️',
  'Translation & Localization': '🌐',
  'Writing & Editing': '✍️',
  'Market Research': '📊',
  'Marketing & Advertising': '📢',
  'Public Relations & Communications': '📢',
  'Import & Export': '🌍',
  'Warehousing': '📦',
  'Packaging & Containers': '📦',
  'Printing': '🖨️',
  'Paper & Forest Products': '📄',
  'Tobacco': '🚬',
  'Biotechnology': '🧬',
  'Design': '🎨',
  'International Trade & Development': '🌍',
  'International Affairs': '🌐',
  'Judiciary': '⚖️',
  'Legislative Office': '📜',
  'Libraries': '📚',
  'Program Development': '📋',
  'Public Relations & Communications': '📢',
  'Railroad Manufacture': '🚂',
  'Shipbuilding': '🚢',
  'Leisure, Travel & Tourism': '✈️',
  'Business Supplies & Equipment': '📦',
  'Outsourcing/Offshoring': '🌍',
  'Alternative Dispute Resolution': '🤝',
  'Executive Office': '👔',
  'Fine Art': '🎨',
  'Fundraising': '💰',
  'Health, Wellness & Fitness': '💪',
  'Information Services': 'ℹ️',
  'Investment Management': '📈',
  'Judiciary': '⚖️',
  'Law Enforcement': '👮',
  'Law Practice': '⚖️',
  'Legal Services': '⚖️',
  'Legislative Office': '📜',
  'Leisure, Travel & Tourism': '✈️',
  'Libraries': '📚',
  'Logistics & Supply Chain': '📦',
  'Luxury Goods & Jewelry': '💎',
  'Machinery': '🔧',
  'Management Consulting': '💼',
  'Maritime': '🚢',
  'Marketing & Advertising': '📢',
  'Market Research': '📊',
  'Mechanical or Industrial Engineering': '⚙️',
  'Media Production': '🎥',
  'Medical Device': '🩺',
  'Medical Practice': '⚕️',
  'Mental Health Care': '🧠',
  'Military': '🎖️',
  'Mining & Metals': '⛏️',
  'Motion Pictures & Film': '🎬',
  'Museums & Institutions': '🏛️',
  'Music': '🎵',
  'Nanotechnology': '🔬',
  'Newspapers': '📰',
  'Nonprofit Organization Management': '🤝',
  'Oil & Energy': '⛽',
  'Online Media': '📱',
  'Outsourcing/Offshoring': '🌍',
  'Package/Freight Delivery': '📦',
  'Packaging & Containers': '📦',
  'Paper & Forest Products': '📄',
  'Performing Arts': '🎭',
  'Pharmaceuticals': '💊',
  'Philanthropy': '💝',
  'Photography': '📸',
  'Plastics': '🔄',
  'Political Organization': '🏛️',
  'Primary/Secondary Education': '📝',
  'Printing': '🖨️',
  'Professional Training & Coaching': '🎯',
  'Program Development': '📋',
  'Public Policy': '📜',
  'Public Relations & Communications': '📢',
  'Public Safety': '🚨',
  'Publishing': '📖',
  'Railroad Manufacture': '🚂',
  'Ranching': '🐄',
  'Real Estate': '🏠',
  'Recreational Facilities & Services': '🎪',
  'Religious Institutions': '⛪',
  'Renewables & Environment': '🌱',
  'Research': '🔬',
  'Restaurants': '🍽️',
  'Retail': '🛍️',
  'Security & Investigations': '🕵️',
  'Semiconductors': '🔌',
  'Shipbuilding': '🚢',
  'Sporting Goods': '⚽',
  'Sports': '⚽',
  'Staffing & Recruiting': '👔',
  'Supermarkets': '🛒',
  'Telecommunications': '📡',
  'Textiles': '🧵',
  'Think Tanks': '💡',
  'Tobacco': '🚬',
  'Translation & Localization': '🌐',
  'Transportation/Trucking/Railroad': '🚂',
  'Travel Arrangements & Tourism': '✈️',
  'Utilities': '⚡',
  'Venture Capital & Private Equity': '💼',
  'Veterinary': '🐾',
  'Warehousing': '📦',
  'Wholesale': '📦',
  'Wine & Spirits': '🍷',
  'Wireless': '📶',
  'Writing & Editing': '✍️'
};

// Company Size Categories
export const COMPANY_SIZES = [
  { value: "small", label: "Small (50 employees or less)" },
  { value: "medium", label: "Medium (51-100 employees)" },
  { value: "large", label: "Large (101-500 employees)" },
  { value: "corporate", label: "Corporate (500+ employees)" },
];

// Company Verification Types
export const VERIFICATION_TYPES = [
  {
    value: "registration",
    label: "Company Registration"
  },
  {
    value: "taxCard",
    label: "Tax Card"
  },
  {
    value: "taxId",
    label: "Tax ID",
  },
];

// Accepted File Types
export const ACCEPTED_FILE_TYPES = {
  images: [
    "image/jpeg",
    "image/png",
  ],
  documents: [
    "application/pdf",
  ],
};

// Free Email Domains
export const FREE_EMAIL_DOMAINS = [
  "gmail.com",
  "yahoo.com",
  "hotmail.com",
  "outlook.com",
  "aol.com",
  "icloud.com",
  "mail.com",
  "protonmail.com",
  "zoho.com",
];

// Users Options
export const usersOptions = [
  {
    value: "company",
    class: "option_company",
    imageUrl: "/images/company-icon.png",
    name: "Company",
    dimension: 130,
    signup: true,
  },
  {
    value: "scad",
    class: "option_scad",
    imageUrl: "/images/scad-icon.png",
    name: "SCAD",
    dimension: 120,
    signup: false,
  },
  {
    value: "faculty",
    class: "option_faculty",
    imageUrl: "/images/faculty-icon.png",
    name: "Faculty",
    dimension: 110,
    signup: false,
  },
  {
    value: "student",
    class: "option_student",
    imageUrl: "/images/student-icon.png",
    name: "Student",
    dimension: 153,
    signup: false,
  },
]