// LinkedIn Industry Categories
export const industries = [
  "Accounting",
  "Airlines/Aviation",
  "Alternative Dispute Resolution",
  "Alternative Medicine",
  "Animation",
  "Apparel & Fashion",
  "Architecture & Planning",
  "Arts & Crafts",
  "Automotive",
  "Aviation & Aerospace",
  "Banking",
  "Biotechnology",
  "Broadcast Media",
  "Building Materials",
  "Business Supplies & Equipment",
  "Capital Markets",
  "Chemicals",
  "Civic & Social Organization",
  "Civil Engineering",
  "Commercial Real Estate",
  "Computer & Network Security",
  "Computer Games",
  "Computer Hardware",
  "Computer Networking",
  "Computer Software",
  "Construction",
  "Consumer Electronics",
  "Consumer Goods",
  "Consumer Services",
  "Cosmetics",
  "Dairy",
  "Defense & Space",
  "Design",
  "E-learning",
  "Education Management",
  "Electrical & Electronic Manufacturing",
  "Entertainment",
  "Environmental Services",
  "Events Services",
  "Executive Office",
  "Facilities Services",
  "Farming",
  "Financial Services",
  "Fine Art",
  "Food & Beverages",
  "Food Production",
  "Fundraising",
  "Furniture",
  "Gambling & Casinos",
  "Glass, Ceramics & Concrete",
  "Government Administration",
  "Government Relations",
  "Graphic Design",
  "Health, Wellness & Fitness",
  "Higher Education",
  "Hospital & Health Care",
  "Hospitality",
  "Human Resources",
  "Import & Export",
  "Individual & Family Services",
  "Industrial Automation",
  "Information Services",
  "Information Technology",
  "Insurance",
  "International Affairs",
  "International Trade & Development",
  "Internet",
  "Investment Banking",
  "Investment Management",
  "Judiciary",
  "Law Enforcement",
  "Law Practice",
  "Legal Services",
  "Legislative Office",
  "Leisure, Travel & Tourism",
  "Libraries",
  "Logistics & Supply Chain",
  "Luxury Goods & Jewelry",
  "Machinery",
  "Management Consulting",
  "Maritime",
  "Marketing & Advertising",
  "Market Research",
  "Mechanical or Industrial Engineering",
  "Media Production",
  "Medical Device",
  "Medical Practice",
  "Mental Health Care",
  "Military",
  "Mining & Metals",
  "Motion Pictures & Film",
  "Museums & Institutions",
  "Music",
  "Nanotechnology",
  "Newspapers",
  "Nonprofit Organization Management",
  "Oil & Energy",
  "Online Media",
  "Outsourcing/Offshoring",
  "Package/Freight Delivery",
  "Packaging & Containers",
  "Paper & Forest Products",
  "Performing Arts",
  "Pharmaceuticals",
  "Philanthropy",
  "Photography",
  "Plastics",
  "Political Organization",
  "Primary/Secondary Education",
  "Printing",
  "Professional Training & Coaching",
  "Program Development",
  "Public Policy",
  "Public Relations & Communications",
  "Public Safety",
  "Publishing",
  "Railroad Manufacture",
  "Ranching",
  "Real Estate",
  "Recreational Facilities & Services",
  "Religious Institutions",
  "Renewables & Environment",
  "Research",
  "Restaurants",
  "Retail",
  "Security & Investigations",
  "Semiconductors",
  "Shipbuilding",
  "Sporting Goods",
  "Sports",
  "Staffing & Recruiting",
  "Software as a Service (SaaS)",
  "Supermarkets",
  "Telecommunications",
  "Textiles",
  "Think Tanks",
  "Tobacco",
  "Translation & Localization",
  "Transportation/Trucking/Railroad",
  "Utilities",
  "Venture Capital & Private Equity",
  "Veterinary",
  "Warehousing",
  "Wholesale",
  "Wine & Spirits",
  "Wireless",
  "Writing & Editing",
];

export const mockCompanies = [
  {
    name: 'Tech Corp',
    industry: 'Technology',
    size: 'Large',
  },
  {
    name: 'Finance Inc',
    industry: 'Finance',
    size: 'Medium',
  },
  {
    name: 'Health LLC',
    industry: 'Healthcare',
    size: 'Small',
  },
  {
    name: 'Microsoft',
    industry: 'Technology',
    size: 'Corporate',
  },
  {
    name: 'LSE',
    industry: 'Electrical Engineering',
    size: 'Medium',
  },
  {
    name: 'Urban Cafe',
    industry: 'Food & Beverage',
    size: 'Small',
  },
  {
    name: 'Global Media',
    industry: 'Entertainment',
    size: 'Corporate',
  },
  {
    name: 'Cloud Networks',
    industry: 'IT Services',
    size: 'Corporate',
  },
  {
    name: 'Creative Designs',
    industry: 'Marketing',
    size: 'Medium',
  },
  {
    name: 'Siemens',
    industry: 'Technology',
    size: 'Medium',
  },
];

export const mockInternships = [
  {
    id: 1,
    title: "Frontend Developer Intern",
    company: "TechVision",
    type: "Full-time",
    locationType: "REMOTE",
    paid: true,
    postedDate: "2 days ago",
    industry: "Technology",
    duration: "3 months",
    skills: ["JavaScript", "React", "CSS"],
    description: "Join our team to work on exciting projects and gain hands-on experience in frontend development."
  },
  {
    id: 2,
    title: "Marketing Coordinator",
    company: "BrandBoost",
    type: "Part-time",
    locationType: "HYBRID",
    paid: false,
    postedDate: "1 week ago",
    industry: "Marketing",
    duration: "6 months",
    skills: ["SEO", "Content Creation", "Social Media"],
    description: "Assist in marketing campaigns and help boost our brand presence online."
  },
  {
    id: 3,
    title: "Data Science Intern",
    company: "Thndr",
    type: "Full-time",
    locationType: "ON-SITE",
    paid: true,
    postedDate: "3 days ago",
    industry: "Technology",
    duration: "4 months",
    skills: ["Python", "Machine Learning", "Data Analysis"],
    description: "Work with our data team to analyze large datasets and derive insights."
  },
  {
    id: 4,
    title: "UX Design Intern",
    company: "CreativeMinds",
    type: "Contract",
    locationType: "REMOTE",
    paid: true,
    postedDate: "5 days ago",
    industry: "Design",
    duration: "4 months",
    skills: ["Figma", "User Research", "Prototyping"],
    description: "Help design user-friendly interfaces and improve user experience for our products."
  },
  {
    id: 5,
    title: "Biomedical Research Assistant",
    company: "HealthInnovate",
    type: "Full-time",
    locationType: "ON-SITE",
    paid: false,
    postedDate: "2 weeks ago",
    industry: "Healthcare",
    duration: "6 months",
    skills: ["Research", "Data Collection", "Analysis"],
    description: "Assist in ongoing biomedical research projects and contribute to data collection and analysis."
  }
];

// Company Size Categories
export const COMPANY_SIZES = [
  { value: "small", label: "Small (50 employees or less)" },
  { value: "medium", label: "Medium (51-100 employees)" },
  { value: "large", label: "Large (101-500 employees)" },
  { value: "corporate", label: "Corporate (500+ employees)" },
];

// Company Verification Types
export const VERIFICATION_TYPES = [
  {
    value: "registration",
    label: "Company Registration"
  },
  {
    value: "taxCard",
    label: "Tax Card"
  },
  {
    value: "taxId",
    label: "Tax ID",
  },
];

// Accepted File Types
export const ACCEPTED_FILE_TYPES = {
  images: [
    "image/jpeg",
    "image/png",
  ],
  documents: [
    "application/pdf",
  ],
};

// Free Email Domains
export const FREE_EMAIL_DOMAINS = [
  "gmail.com",
  "yahoo.com",
  "hotmail.com",
  "outlook.com",
  "aol.com",
  "icloud.com",
  "mail.com",
  "protonmail.com",
  "zoho.com",
];

// Users Options
export const usersOptions = [
  {
    value: "company",
    class: "option_company",
    imageUrl: "/images/company.png",
    name: "Company",
    dimension: 130,
    signup: true,
  },
  {
    value: "scad",
    class: "option_scad",
    imageUrl: "/images/scad.png",
    name: "SCAD",
    dimension: 120,
    signup: false,
  },
  {
    value: "faculty",
    class: "option_faculty",
    imageUrl: "/images/faculty.png",
    name: "Faculty",
    dimension: 110,
    signup: false,
  },
  {
    value: "student",
    class: "option_student",
    imageUrl: "/images/student.png",
    name: "Student",
    dimension: 153,
    signup: false,
  },
]